
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-courses-staff
owner: ucsb-cs156-s23
repo_name: proj-courses-staff
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-spike-new-grade-data-repo","number":3,"title":"Pc spike new grade data repo","url":"https://github.com/ucsb-cs156-s23/proj-courses-staff/pull/3"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-spike-on-background-job-for-grade-data","number":2,"title":"Pc spike on background job for grade data","url":"https://github.com/ucsb-cs156-s23/proj-courses-staff/pull/2"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-spike-on-grade-data-csv-upload","number":1,"title":"pc - spike on uploading grade data via csv","url":"https://github.com/ucsb-cs156-s23/proj-courses-staff/pull/1"}]
